<?php

require $_SERVER['DOCUMENT_ROOT'].'/bitrix/header.php';

$APPLICATION->SetPageProperty('keywords', 'Manom');
$APPLICATION->SetPageProperty('description', 'Manom');
$APPLICATION->SetPageProperty('title', 'Manom');
$APPLICATION->SetTitle('Manom');

global $productsOfTheDayFilter;
$productsOfTheDayFilter = array(
    '!PROPERTY_PRODUCT_OF_THE_DAY' => false,
    '>CATALOG_PRICE_1' => 0,
);

global $saleFilter;
$saleFilter = array(
    '!PROPERTY_SELL_PROD' => false,
    '>CATALOG_PRICE_1' => 0,
);

global $newFilter;
$newFilter = array(
    '!PROPERTY_NEW_PRODUCT' => false,
    '>CATALOG_PRICE_1' => 0,
);
?>
<div class="content content--index">
    <!-- Слайдер -->
    <section class='first-scr'>
        <div class="container">
            <div class="row first-scr__block">
                <?php $APPLICATION->IncludeComponent(
                    'bitrix:news.list',
                    'main_slider',
                    Array(
                        'DISPLAY_DATE' => 'Y',
                        'DISPLAY_NAME' => 'Y',
                        'DISPLAY_PICTURE' => 'Y',
                        'DISPLAY_PREVIEW_TEXT' => 'Y',
                        'AJAX_MODE' => 'N',
                        'IBLOCK_TYPE' => 'content',
                        'IBLOCK_ID' => 1,
                        'NEWS_COUNT' => '20',
                        'SORT_BY1' => 'ACTIVE_FROM',
                        'SORT_ORDER1' => 'DESC',
                        'SORT_BY2' => 'SORT',
                        'SORT_ORDER2' => 'ASC',
                        'FILTER_NAME' => '',
                        'FIELD_CODE' => array('SLIDER_LINK'),
                        'PROPERTY_CODE' => array('SLIDER_LINK'),
                        'CHECK_DATES' => 'Y',
                        'DETAIL_URL' => '',
                        'PREVIEW_TRUNCATE_LEN' => '',
                        'ACTIVE_DATE_FORMAT' => '',
                        'SET_TITLE' => 'N',
                        'SET_STATUS_404' => 'N',
                        'INCLUDE_IBLOCK_INTO_CHAIN' => 'N',
                        'ADD_SECTIONS_CHAIN' => 'N',
                        'HIDE_LINK_WHEN_NO_DETAIL' => 'N',
                        'PARENT_SECTION' => '',
                        'PARENT_SECTION_CODE' => '',
                        'CACHE_TYPE' => 'A',
                        'CACHE_TIME' => '36000000',
                        'CACHE_NOTES' => '',
                        'CACHE_FILTER' => 'N',
                        'CACHE_GROUPS' => 'N',
                        'DISPLAY_TOP_PAGER' => 'N',
                        'DISPLAY_BOTTOM_PAGER' => 'N',
                        'PAGER_TITLE' => 'Слайдер',
                        'PAGER_SHOW_ALWAYS' => 'N',
                        'PAGER_TEMPLATE' => '',
                        'PAGER_DESC_NUMBERING' => 'N',
                        'PAGER_DESC_NUMBERING_CACHE_TIME' => '36000',
                        'PAGER_SHOW_ALL' => 'N',
                        'AJAX_OPTION_JUMP' => 'N',
                        'AJAX_OPTION_STYLE' => 'Y',
                        'AJAX_OPTION_HISTORY' => 'N',
                        'AJAX_OPTION_ADDITIONAL' => '',
                    )
                ); ?>
                <div class="first-scr__right">
                    <?php $APPLICATION->IncludeComponent(
                        'bitrix:catalog.section',
                        'item_day',
                        array(
                            'ACTION_VARIABLE' => '',
                            'ADD_PICT_PROP' => '',
                            'ADD_PROPERTIES_TO_BASKET' => 'N',
                            'ADD_SECTIONS_CHAIN' => 'N',
                            'ADD_TO_BASKET_ACTION' => '',
                            'AJAX_MODE' => 'N',
                            'AJAX_OPTION_ADDITIONAL' => '',
                            'AJAX_OPTION_HISTORY' => 'N',
                            'AJAX_OPTION_JUMP' => 'N',
                            'AJAX_OPTION_STYLE' => 'N',
                            'BACKGROUND_IMAGE' => '',
                            'BASKET_URL' => '',
                            'BRAND_PROPERTY' => '',
                            'BROWSER_TITLE' => '',
                            'CACHE_FILTER' => 'N',
                            'CACHE_GROUPS' => 'Y',
                            'CACHE_TIME' => 36000000,
                            'CACHE_TYPE' => 'N',
                            'COMPATIBLE_MODE' => 'Y',
                            'CONVERT_CURRENCY' => 'Y',
                            'CURRENCY_ID' => 'RUB',
                            'CUSTOM_FILTER' => '',
                            'DATA_LAYER_NAME' => '',
                            'DETAIL_URL' => '',
                            'DISABLE_INIT_JS_IN_COMPONENT' => 'N',
                            'DISCOUNT_PERCENT_POSITION' => '',
                            'DISPLAY_BOTTOM_PAGER' => 'N',
                            'DISPLAY_TOP_PAGER' => 'N',
                            'ELEMENT_SORT_FIELD' => 'sort',
                            'ELEMENT_SORT_FIELD2' => 'id',
                            'ELEMENT_SORT_ORDER' => 'asc',
                            'ELEMENT_SORT_ORDER2' => 'desc',
                            'ENLARGE_PRODUCT' => '',
                            'ENLARGE_PROP' => '',
                            'FILTER_NAME' => 'productsOfTheDayFilter',
                            'HIDE_NOT_AVAILABLE' => 'Y',
                            'HIDE_NOT_AVAILABLE_OFFERS' => 'Y',
                            'IBLOCK_ID' => 6,
                            'IBLOCK_TYPE' => 'catalog',
                            'INCLUDE_SUBSECTIONS' => 'Y',
                            'LABEL_PROP' => array(),
                            'LABEL_PROP_MOBILE' => '',
                            'LABEL_PROP_POSITION' => '',
                            'LAZY_LOAD' => 'N',
                            'LINE_ELEMENT_COUNT' => 0,
                            'LOAD_ON_SCROLL' => 'N',
                            'MESSAGE_404' => '',
                            'MESS_BTN_ADD_TO_BASKET' => '',
                            'MESS_BTN_BUY' => '',
                            'MESS_BTN_DETAIL' => '',
                            'MESS_BTN_LAZY_LOAD' => '',
                            'MESS_BTN_SUBSCRIBE' => '',
                            'MESS_NOT_AVAILABLE' => '',
                            'META_DESCRIPTION' => '',
                            'META_KEYWORDS' => '',
                            'OFFERS_CART_PROPERTIES' => array('MORE_PHOTO'),
                            'OFFERS_FIELD_CODE' => array(),
                            'OFFERS_LIMIT' => 0,
                            'OFFERS_PROPERTY_CODE' => array('MORE_PHOTO'),
                            'OFFERS_SORT_FIELD' => 'sort',
                            'OFFERS_SORT_FIELD2' => 'id',
                            'OFFERS_SORT_ORDER' => 'asc',
                            'OFFERS_SORT_ORDER2' => 'desc',
                            'OFFER_ADD_PICT_PROP' => '',
                            'OFFER_TREE_PROPS' => array('MORE_PHOTO'),
                            'PAGER_BASE_LINK_ENABLE' => 'N',
                            'PAGER_DESC_NUMBERING' => 'N',
                            'PAGER_DESC_NUMBERING_CACHE_TIME' => 36000,
                            'PAGER_SHOW_ALL' => 'N',
                            'PAGER_SHOW_ALWAYS' => 'N',
                            'PAGER_TEMPLATE' => '',
                            'PAGER_TITLE' => 'Товары',
                            'PAGE_ELEMENT_COUNT' => 6,
                            'PARTIAL_PRODUCT_PROPERTIES' => 'N',
                            'PRICE_CODE' => array('Розничная'),
                            'PRICE_VAT_INCLUDE' => 'Y',
                            'PRODUCT_BLOCKS_ORDER' => '',
                            'PRODUCT_DISPLAY_MODE' => 'N',
                            'PRODUCT_ID_VARIABLE' => '',
                            'PRODUCT_PROPERTIES' => array('MORE_PHOTO'),
                            'PRODUCT_PROPS_VARIABLE' => '',
                            'PRODUCT_QUANTITY_VARIABLE' => '',
                            'PRODUCT_ROW_VARIANTS' => '',
                            'PRODUCT_SUBSCRIPTION' => 'N',
                            'PROPERTY_CODE' => array('MORE_PHOTO'),
                            'PROPERTY_CODE_MOBILE' => array('MORE_PHOTO'),
                            'RCM_PROD_ID' => '',
                            'RCM_TYPE' => '',
                            'SECTION_CODE' => '',
                            'SECTION_ID' => '',
                            'SECTION_ID_VARIABLE' => '',
                            'SECTION_URL' => '',
                            'SECTION_USER_FIELDS' => array(),
                            'SEF_MODE' => 'N',
                            'SET_BROWSER_TITLE' => 'N',
                            'SET_LAST_MODIFIED' => 'N',
                            'SET_META_DESCRIPTION' => 'N',
                            'SET_META_KEYWORDS' => 'N',
                            'SET_STATUS_404' => 'N',
                            'SET_TITLE' => 'N',
                            'SHOW_404' => 'N',
                            'SHOW_ALL_WO_SECTION' => 'Y',
                            'SHOW_CLOSE_POPUP' => 'N',
                            'SHOW_DISCOUNT_PERCENT' => 'N',
                            'SHOW_FROM_SECTION' => 'N',
                            'SHOW_MAX_QUANTITY' => 'N',
                            'SHOW_OLD_PRICE' => 'N',
                            'SHOW_PRICE_COUNT' => '',
                            'SHOW_SLIDER' => 'N',
                            'SLIDER_INTERVAL' => 0,
                            'SLIDER_PROGRESS' => 'N',
                            'TEMPLATE_THEME' => '',
                            'USE_ENHANCED_ECOMMERCE' => 'N',
                            'USE_MAIN_ELEMENT_SECTION' => 'N',
                            'USE_PRICE_COUNT' => 'Y',
                            'USE_PRODUCT_QUANTITY' => 'N',
                            'DISPLAY_COMPARE' => 'N',
                        ),
                        false
                    ); ?>
                </div>
            </div>
        </div>
    </section>

    <?php /*
    <!-- Выгоды -->
    <section class="benefit">
        <?php $APPLICATION->IncludeComponent(
            'bitrix:news.list',
            'benefit',
            Array(
                'DISPLAY_DATE' => 'Y',
                'DISPLAY_NAME' => 'Y',
                'DISPLAY_PICTURE' => 'Y',
                'DISPLAY_PREVIEW_TEXT' => 'Y',
                'AJAX_MODE' => 'N',
                'IBLOCK_TYPE' => 'content',
                'IBLOCK_ID' => '2',
                'NEWS_COUNT' => '20',
                'SORT_BY1' => 'ACTIVE_FROM',
                'SORT_ORDER1' => 'DESC',
                'SORT_BY2' => 'SORT',
                'SORT_ORDER2' => 'ASC',
                'FILTER_NAME' => '',
                'FIELD_CODE' => array('SLIDER_LINK'),
                'PROPERTY_CODE' => array('SLIDER_LINK'),
                'CHECK_DATES' => 'Y',
                'DETAIL_URL' => '',
                'PREVIEW_TRUNCATE_LEN' => '',
                'ACTIVE_DATE_FORMAT' => '',
                'SET_TITLE' => 'N',
                'SET_STATUS_404' => 'N',
                'INCLUDE_IBLOCK_INTO_CHAIN' => 'N',
                'ADD_SECTIONS_CHAIN' => 'N',
                'HIDE_LINK_WHEN_NO_DETAIL' => 'N',
                'PARENT_SECTION' => '',
                'PARENT_SECTION_CODE' => '',
                'CACHE_TYPE' => 'A',
                'CACHE_TIME' => '36000000',
                'CACHE_NOTES' => '',
                'CACHE_FILTER' => 'N',
                'CACHE_GROUPS' => 'N',
                'DISPLAY_TOP_PAGER' => 'N',
                'DISPLAY_BOTTOM_PAGER' => 'N',
                'PAGER_TITLE' => 'Слайдер',
                'PAGER_SHOW_ALWAYS' => 'N',
                'PAGER_TEMPLATE' => '',
                'PAGER_DESC_NUMBERING' => 'N',
                'PAGER_DESC_NUMBERING_CACHE_TIME' => '36000',
                'PAGER_SHOW_ALL' => 'N',
                'AJAX_OPTION_JUMP' => 'N',
                'AJAX_OPTION_STYLE' => 'Y',
                'AJAX_OPTION_HISTORY' => 'N',
                'AJAX_OPTION_ADDITIONAL' => '',
            )
        ); ?>
    </section>
    */ ?>

    <!-- Товары по акции -->
    <?php $APPLICATION->IncludeComponent(
        'bitrix:catalog.section',
        'product_stock',
        array(
            'ACTION_VARIABLE' => '',
            'ADD_PICT_PROP' => '',
            'ADD_PROPERTIES_TO_BASKET' => 'N',
            'ADD_SECTIONS_CHAIN' => 'N',
            'ADD_TO_BASKET_ACTION' => '',
            'AJAX_MODE' => 'N',
            'AJAX_OPTION_ADDITIONAL' => '',
            'AJAX_OPTION_HISTORY' => 'N',
            'AJAX_OPTION_JUMP' => 'N',
            'AJAX_OPTION_STYLE' => 'N',
            'BACKGROUND_IMAGE' => '',
            'BASKET_URL' => '',
            'BRAND_PROPERTY' => '',
            'BROWSER_TITLE' => '',
            'CACHE_FILTER' => 'N',
            'CACHE_GROUPS' => 'Y',
            'CACHE_TIME' => 36000000,
            'CACHE_TYPE' => 'N',
            'COMPATIBLE_MODE' => 'Y',
            'CONVERT_CURRENCY' => 'Y',
            'CURRENCY_ID' => 'RUB',
            'CUSTOM_FILTER' => '',
            'DATA_LAYER_NAME' => '',
            'DETAIL_URL' => '',
            'DISABLE_INIT_JS_IN_COMPONENT' => 'N',
            'DISCOUNT_PERCENT_POSITION' => '',
            'DISPLAY_BOTTOM_PAGER' => 'N',
            'DISPLAY_TOP_PAGER' => 'N',
            'ELEMENT_SORT_FIELD' => 'sort',
            'ELEMENT_SORT_FIELD2' => 'id',
            'ELEMENT_SORT_ORDER' => 'asc',
            'ELEMENT_SORT_ORDER2' => 'desc',
            'ENLARGE_PRODUCT' => '',
            'ENLARGE_PROP' => '',
            'FILTER_NAME' => 'saleFilter',
            'HIDE_NOT_AVAILABLE' => 'Y',
            'HIDE_NOT_AVAILABLE_OFFERS' => 'Y',
            'IBLOCK_ID' => 6,
            'IBLOCK_TYPE' => 'catalog',
            'INCLUDE_SUBSECTIONS' => 'Y',
            'LABEL_PROP' => array(),
            'LABEL_PROP_MOBILE' => '',
            'LABEL_PROP_POSITION' => '',
            'LAZY_LOAD' => 'Y',
            'LINE_ELEMENT_COUNT' => 0,
            'LOAD_ON_SCROLL' => 'N',
            'MESSAGE_404' => '',
            'MESS_BTN_ADD_TO_BASKET' => '',
            'MESS_BTN_BUY' => '',
            'MESS_BTN_DETAIL' => '',
            'MESS_BTN_LAZY_LOAD' => '',
            'MESS_BTN_SUBSCRIBE' => '',
            'MESS_NOT_AVAILABLE' => '',
            'META_DESCRIPTION' => '',
            'META_KEYWORDS' => '-',
            'OFFERS_CART_PROPERTIES' => array('MORE_PHOTO'),
            'OFFERS_FIELD_CODE' => array(),
            'OFFERS_LIMIT' => 0,
            'OFFERS_PROPERTY_CODE' => array('MORE_PHOTO'),
            'OFFERS_SORT_FIELD' => 'sort',
            'OFFERS_SORT_FIELD2' => 'id',
            'OFFERS_SORT_ORDER' => 'asc',
            'OFFERS_SORT_ORDER2' => 'desc',
            'OFFER_ADD_PICT_PROP' => '',
            'OFFER_TREE_PROPS' => array('MORE_PHOTO'),
            'PAGER_BASE_LINK_ENABLE' => 'N',
            'PAGER_DESC_NUMBERING' => 'N',
            'PAGER_DESC_NUMBERING_CACHE_TIME' => 36000,
            'PAGER_SHOW_ALL' => 'N',
            'PAGER_SHOW_ALWAYS' => 'N',
            'PAGER_TEMPLATE' => '',
            'PAGER_TITLE' => 'Товары',
            'PAGE_ELEMENT_COUNT' => 6,
            'PARTIAL_PRODUCT_PROPERTIES' => 'N',
            'PRICE_CODE' => array('Розничная'),
            'PRICE_VAT_INCLUDE' => 'Y',
            'PRODUCT_BLOCKS_ORDER' => '',
            'PRODUCT_DISPLAY_MODE' => 'N',
            'PRODUCT_ID_VARIABLE' => '',
            'PRODUCT_PROPERTIES' => array('MORE_PHOTO'),
            'PRODUCT_PROPS_VARIABLE' => '',
            'PRODUCT_QUANTITY_VARIABLE' => '',
            'PRODUCT_ROW_VARIANTS' => '',
            'PRODUCT_SUBSCRIPTION' => 'N',
            'PROPERTY_CODE' => array('MORE_PHOTO'),
            'PROPERTY_CODE_MOBILE' => array('MORE_PHOTO'),
            'RCM_PROD_ID' => '',
            'RCM_TYPE' => '',
            'SECTION_CODE' => '',
            'SECTION_ID' => '',
            'SECTION_ID_VARIABLE' => '',
            'SECTION_URL' => '',
            'SECTION_USER_FIELDS' => array(),
            'SEF_MODE' => 'N',
            'SET_BROWSER_TITLE' => 'N',
            'SET_LAST_MODIFIED' => 'N',
            'SET_META_DESCRIPTION' => 'N',
            'SET_META_KEYWORDS' => 'N',
            'SET_STATUS_404' => 'N',
            'SET_TITLE' => 'N',
            'SHOW_404' => 'N',
            'SHOW_ALL_WO_SECTION' => 'Y',
            'SHOW_CLOSE_POPUP' => 'N',
            'SHOW_DISCOUNT_PERCENT' => 'N',
            'SHOW_FROM_SECTION' => 'N',
            'SHOW_MAX_QUANTITY' => 'N',
            'SHOW_OLD_PRICE' => 'N',
            'SHOW_PRICE_COUNT' => 1,
            'SHOW_SLIDER' => 'N',
            'SLIDER_INTERVAL' => 3000,
            'SLIDER_PROGRESS' => 'N',
            'TEMPLATE_THEME' => '',
            'USE_ENHANCED_ECOMMERCE' => 'N',
            'USE_MAIN_ELEMENT_SECTION' => 'N',
            'USE_PRICE_COUNT' => 'Y',
            'USE_PRODUCT_QUANTITY' => 'N',
            'DISPLAY_COMPARE' => 'N',
        ),
        false
    ); ?>

    <!-- Новинки -->
    <?php $APPLICATION->IncludeComponent(
        'bitrix:catalog.section',
        'new_product',
        array(
            'ACTION_VARIABLE' => '',
            'ADD_PICT_PROP' => '',
            'ADD_PROPERTIES_TO_BASKET' => 'N',
            'ADD_SECTIONS_CHAIN' => 'N',
            'ADD_TO_BASKET_ACTION' => '',
            'AJAX_MODE' => 'N',
            'AJAX_OPTION_ADDITIONAL' => '',
            'AJAX_OPTION_HISTORY' => 'N',
            'AJAX_OPTION_JUMP' => 'N',
            'AJAX_OPTION_STYLE' => 'N',
            'BACKGROUND_IMAGE' => '',
            'BASKET_URL' => '',
            'BRAND_PROPERTY' => '',
            'BROWSER_TITLE' => '',
            'CACHE_FILTER' => 'N',
            'CACHE_GROUPS' => 'Y',
            'CACHE_TIME' => 36000000,
            'CACHE_TYPE' => 'A',
            'COMPATIBLE_MODE' => 'Y',
            'CONVERT_CURRENCY' => 'Y',
            'CURRENCY_ID' => 'RUB',
            'CUSTOM_FILTER' => '',
            'DATA_LAYER_NAME' => '',
            'DETAIL_URL' => '',
            'DISABLE_INIT_JS_IN_COMPONENT' => 'N',
            'DISCOUNT_PERCENT_POSITION' => '',
            'DISPLAY_BOTTOM_PAGER' => 'N',
            'DISPLAY_TOP_PAGER' => 'N',
            'ELEMENT_SORT_FIELD' => 'sort',
            'ELEMENT_SORT_FIELD2' => 'id',
            'ELEMENT_SORT_ORDER' => 'asc',
            'ELEMENT_SORT_ORDER2' => 'desc',
            'ENLARGE_PRODUCT' => '',
            'ENLARGE_PROP' => '',
            'FILTER_NAME' => 'newFilter',
            'HIDE_NOT_AVAILABLE' => 'Y',
            'HIDE_NOT_AVAILABLE_OFFERS' => 'Y',
            'IBLOCK_ID' => 6,
            'IBLOCK_TYPE' => 'catalog',
            'INCLUDE_SUBSECTIONS' => 'Y',
            'LABEL_PROP' => array(),
            'LABEL_PROP_MOBILE' => '',
            'LABEL_PROP_POSITION' => '',
            'LAZY_LOAD' => 'N',
            'LINE_ELEMENT_COUNT' => 0,
            'LOAD_ON_SCROLL' => 'N',
            'MESSAGE_404' => '',
            'MESS_BTN_ADD_TO_BASKET' => '',
            'MESS_BTN_BUY' => '',
            'MESS_BTN_DETAIL' => '',
            'MESS_BTN_LAZY_LOAD' => '',
            'MESS_BTN_SUBSCRIBE' => '',
            'MESS_NOT_AVAILABLE' => '',
            'META_DESCRIPTION' => '',
            'META_KEYWORDS' => '',
            'OFFERS_CART_PROPERTIES' => array('MORE_PHOTO'),
            'OFFERS_FIELD_CODE' => array(),
            'OFFERS_LIMIT' => 0,
            'OFFERS_PROPERTY_CODE' => array('MORE_PHOTO'),
            'OFFERS_SORT_FIELD' => 'sort',
            'OFFERS_SORT_FIELD2' => 'id',
            'OFFERS_SORT_ORDER' => 'asc',
            'OFFERS_SORT_ORDER2' => 'desc',
            'OFFER_ADD_PICT_PROP' => '',
            'OFFER_TREE_PROPS' => array('MORE_PHOTO'),
            'PAGER_BASE_LINK_ENABLE' => 'N',
            'PAGER_DESC_NUMBERING' => 'N',
            'PAGER_DESC_NUMBERING_CACHE_TIME' => 36000,
            'PAGER_SHOW_ALL' => 'N',
            'PAGER_SHOW_ALWAYS' => 'N',
            'PAGER_TEMPLATE' => '',
            'PAGER_TITLE' => 'Товары',
            'PAGE_ELEMENT_COUNT' => 6,
            'PARTIAL_PRODUCT_PROPERTIES' => 'N',
            'PRICE_CODE' => array('Розничная'),
            'PRICE_VAT_INCLUDE' => 'Y',
            'PRODUCT_BLOCKS_ORDER' => '',
            'PRODUCT_DISPLAY_MODE' => 'N',
            'PRODUCT_ID_VARIABLE' => '',
            'PRODUCT_PROPERTIES' => array('MORE_PHOTO'),
            'PRODUCT_PROPS_VARIABLE' => '',
            'PRODUCT_QUANTITY_VARIABLE' => '',
            'PRODUCT_ROW_VARIANTS' => '',
            'PRODUCT_SUBSCRIPTION' => 'N',
            'PROPERTY_CODE' => array('MORE_PHOTO'),
            'PROPERTY_CODE_MOBILE' => array('MORE_PHOTO'),
            'RCM_PROD_ID' => '',
            'RCM_TYPE' => '',
            'SECTION_CODE' => '',
            'SECTION_ID' => '',
            'SECTION_ID_VARIABLE' => '',
            'SECTION_URL' => '',
            'SECTION_USER_FIELDS' => array(),
            'SEF_MODE' => 'N',
            'SET_BROWSER_TITLE' => 'N',
            'SET_LAST_MODIFIED' => 'N',
            'SET_META_DESCRIPTION' => 'N',
            'SET_META_KEYWORDS' => 'N',
            'SET_STATUS_404' => 'N',
            'SET_TITLE' => 'N',
            'SHOW_404' => 'N',
            'SHOW_ALL_WO_SECTION' => 'Y',
            'SHOW_CLOSE_POPUP' => 'N',
            'SHOW_DISCOUNT_PERCENT' => 'N',
            'SHOW_FROM_SECTION' => 'N',
            'SHOW_MAX_QUANTITY' => 'N',
            'SHOW_OLD_PRICE' => 'N',
            'SHOW_PRICE_COUNT' => 1,
            'SHOW_SLIDER' => 'N',
            'SLIDER_INTERVAL' => 3000,
            'SLIDER_PROGRESS' => 'N',
            'TEMPLATE_THEME' => '',
            'USE_ENHANCED_ECOMMERCE' => 'N',
            'USE_MAIN_ELEMENT_SECTION' => 'N',
            'USE_PRICE_COUNT' => 'Y',
            'USE_PRODUCT_QUANTITY' => 'N',
            'DISPLAY_COMPARE' => 'N',
        ),
        false
    ); ?>

    <?php /*
    <!-- Бренды -->
    <section class="brands">
        <?php $APPLICATION->IncludeComponent(
            'bitrix:news.list',
            'brand',
            Array(
                'DISPLAY_DATE' => 'Y',
                'DISPLAY_NAME' => 'Y',
                'DISPLAY_PICTURE' => 'Y',
                'DISPLAY_PREVIEW_TEXT' => 'Y',
                'AJAX_MODE' => 'N',
                'IBLOCK_TYPE' => 'content',
                'IBLOCK_ID' => '3',
                'NEWS_COUNT' => '20',
                'SORT_BY1' => 'ACTIVE_FROM',
                'SORT_ORDER1' => 'DESC',
                'SORT_BY2' => 'SORT',
                'SORT_ORDER2' => 'ASC',
                'FILTER_NAME' => '',
                'FIELD_CODE' => array('SLIDER_LINK'),
                'PROPERTY_CODE' => array('SLIDER_LINK'),
                'CHECK_DATES' => 'Y',
                'DETAIL_URL' => '',
                'PREVIEW_TRUNCATE_LEN' => '',
                'ACTIVE_DATE_FORMAT' => '',
                'SET_TITLE' => 'N',
                'SET_STATUS_404' => 'N',
                'INCLUDE_IBLOCK_INTO_CHAIN' => 'N',
                'ADD_SECTIONS_CHAIN' => 'N',
                'HIDE_LINK_WHEN_NO_DETAIL' => 'N',
                'PARENT_SECTION' => '',
                'PARENT_SECTION_CODE' => '',
                'CACHE_TYPE' => 'A',
                'CACHE_TIME' => '36000000',
                'CACHE_NOTES' => '',
                'CACHE_FILTER' => 'N',
                'CACHE_GROUPS' => 'N',
                'DISPLAY_TOP_PAGER' => 'N',
                'DISPLAY_BOTTOM_PAGER' => 'N',
                'PAGER_TITLE' => 'Слайдер',
                'PAGER_SHOW_ALWAYS' => 'N',
                'PAGER_TEMPLATE' => '',
                'PAGER_DESC_NUMBERING' => 'N',
                'PAGER_DESC_NUMBERING_CACHE_TIME' => '36000',
                'PAGER_SHOW_ALL' => 'N',
                'AJAX_OPTION_JUMP' => 'N',
                'AJAX_OPTION_STYLE' => 'Y',
                'AJAX_OPTION_HISTORY' => 'N',
                'AJAX_OPTION_ADDITIONAL' => '',
            )
        ); ?>
    </section>
    */ ?>

    <?php /*
    <!-- Бестселлеры -->
    <section class="bestsellers">
        <?php $APPLICATION->IncludeComponent(
            'bitrix:sale.bestsellers',
            'bestmanom',
            array(
                'LINE_ELEMENT_COUNT' => '3',
                'TEMPLATE_THEME' => 'blue',
                'BY' => 'QUANTITY',
                'PERIOD' => '0',
                'FILTER' => array(
                    0 => 'N',
                    1 => 'F',
                ),
                'CACHE_TYPE' => 'A',
                'CACHE_TIME' => '86400',
                'AJAX_MODE' => 'N',
                'DETAIL_URL' => '',
                'BASKET_URL' => '/cart/',
                'ACTION_VARIABLE' => 'action',
                'PRODUCT_ID_VARIABLE' => 'id',
                'PRODUCT_QUANTITY_VARIABLE' => 'quantity',
                'ADD_PROPERTIES_TO_BASKET' => 'Y',
                'PRODUCT_PROPS_VARIABLE' => 'prop',
                'PARTIAL_PRODUCT_PROPERTIES' => 'N',
                'DISPLAY_COMPARE' => 'N',
                'SHOW_OLD_PRICE' => 'N',
                'SHOW_DISCOUNT_PERCENT' => 'N',
                'PRICE_CODE' => array(),
                'SHOW_PRICE_COUNT' => '1',
                'PRODUCT_SUBSCRIPTION' => 'N',
                'PRICE_VAT_INCLUDE' => 'Y',
                'USE_PRODUCT_QUANTITY' => 'N',
                'SHOW_NAME' => 'Y',
                'SHOW_IMAGE' => 'Y',
                'MESS_BTN_BUY' => 'Купить',
                'MESS_BTN_DETAIL' => 'Подробнее',
                'MESS_NOT_AVAILABLE' => 'Нет в наличии',
                'MESS_BTN_SUBSCRIBE' => 'Подписаться',
                'PAGE_ELEMENT_COUNT' => '30',
                'SHOW_PRODUCTS_3' => 'Y',
                'PROPERTY_CODE_3' => array(
                    0 => 'MANUFACTURER',
                    1 => 'MATERIAL',
                ),
                'CART_PROPERTIES_3' => array(
                    0 => 'CORNER',
                ),
                'ADDITIONAL_PICT_PROP_3' => 'MORE_PHOTO',
                'LABEL_PROP_3' => 'SPECIALOFFER',
                'PROPERTY_CODE_4' => array(
                    0 => 'COLOR',
                ),
                'CART_PROPERTIES_4' => '',
                'OFFER_TREE_PROPS_4' => array(),
                'HIDE_NOT_AVAILABLE' => 'N',
                'CONVERT_CURRENCY' => 'Y',
                'CURRENCY_ID' => 'RUB',
                'AJAX_OPTION_JUMP' => 'N',
                'AJAX_OPTION_STYLE' => 'Y',
                'AJAX_OPTION_HISTORY' => 'N',
                'COMPONENT_TEMPLATE' => 'bestmanom',
                'AJAX_OPTION_ADDITIONAL' => '',
                'SHOW_PRODUCTS_6' => 'Y',
                'PROPERTY_CODE_6' => array(),
                'CART_PROPERTIES_6' => array(),
                'ADDITIONAL_PICT_PROP_6' => 'MORE_PHOTO',
                'LABEL_PROP_6' => '-',
                'PROPERTY_CODE_7' => array(),
                'CART_PROPERTIES_7' => array(),
                'ADDITIONAL_PICT_PROP_7' => 'MORE_PHOTO',
                'OFFER_TREE_PROPS_7' => array(),
            ),
            false
        ); ?>
    </section>
    */ ?>

    <!-- О магазине -->
    <section id="about-shops" class="about-shops">
        <div class="container">
            <?php $APPLICATION->IncludeFile(
                '/include_area/about_shop.php',
                Array(),
                Array('MODE' => 'html')
            ); ?>
        </div>
    </section>
</div>
<script>
	$(function() {
		window.gtmActions.initCommonData(<?=GTM::getDataJS("home")?>);
	});
</script>
<?php
require $_SERVER['DOCUMENT_ROOT'].'/bitrix/footer.php';
?>