<?php

require $_SERVER['DOCUMENT_ROOT'].'/bitrix/header.php';

$APPLICATION->SetTitle('Каталог');

global $catalogFilter;
$catalogFilter = array_merge($catalogFilter, array('>CATALOG_PRICE_1' => 0));
?>
<div class='content'>
    <?php $APPLICATION->IncludeComponent(
        'bitrix:catalog',
        'catalog2',
        Array(
            'ADD_ELEMENT_CHAIN' => 'Y',
            'ADD_PICT_PROP' => '',
            'ADD_PROPERTIES_TO_BASKET' => 'N',
            'ADD_SECTIONS_CHAIN' => 'Y',
            'AJAX_MODE' => 'N',
            'AJAX_OPTION_ADDITIONAL' => '',
            'AJAX_OPTION_HISTORY' => 'N',
            'AJAX_OPTION_JUMP' => 'N',
            'AJAX_OPTION_STYLE' => 'N',
            'BASKET_URL' => '',
            'BIG_DATA_RCM_TYPE' => '',
            'CACHE_FILTER' => 'N',
            'CACHE_GROUPS' => 'Y',
            'CACHE_TIME' => 36000000,
            'CACHE_TYPE' => 'A',
            'COMMON_ADD_TO_BASKET_ACTION' => '',
            'COMMON_SHOW_CLOSE_POPUP' => 'N',
            'COMPATIBLE_MODE' => 'Y',
            'CONVERT_CURRENCY' => 'N',
            'DETAIL_ADD_DETAIL_TO_SLIDER' => 'N',
            'DETAIL_ADD_TO_BASKET_ACTION' => array(),
            'DETAIL_ADD_TO_BASKET_ACTION_PRIMARY' => array(),
            'DETAIL_BACKGROUND_IMAGE' => '',
            'DETAIL_BRAND_USE' => 'N',
            'DETAIL_BROWSER_TITLE' => '',
            'DETAIL_CHECK_SECTION_ID_VARIABLE' => 'N',
            'DETAIL_DETAIL_PICTURE_MODE' => array(),
            'DETAIL_DISPLAY_NAME' => 'N',
            'DETAIL_DISPLAY_PREVIEW_TEXT_MODE' => '',
            'DETAIL_IMAGE_RESOLUTION' => '',
            'DETAIL_MAIN_BLOCK_OFFERS_PROPERTY_CODE' => array(
                'this_prod_model',
                'watch_display_size',
                'HDD',
                'BLOG_POST_ID',
                'CML2_ARTICLE',
                'CML2_BASE_UNIT',
                'size_list',
                'MORE_PHOTO',
                'BLOG_COMMENTS_CNT',
                'material_list',
                'NOT_EXPORT_YM',
                'OS',
                'CML2_MANUFACTURER',
                'PROC',
                'SCREEN_RES',
                'laptop_series',
                'FILES',
                'COLOR_REF',
                'ciferblat',
                'BUNDLE_BOX',
                'CML2_BAR_CODE',
            ),
            'DETAIL_MAIN_BLOCK_PROPERTY_CODE' => array(
                'model',
                'CML2_ARTICLE',
                'SCREEN_SiZE',
                'SCREEN_RESOLUTION',
                'SCREEN_TYPE',
                'display_density_ppi',
                'DELIVERY_DETAIL_CART',
                'BLOG_POST_ID',
                'lan_socketrj45',
                'microsoft',
                'display_multitouch_option',
                'touchbar_apple',
                'automatic_on',
                'movements_accelerometer',
                'ACESS',
                'acoustic_type',
                'audio',
                'id_verification',
                'batteries_inbox',
                'BATTARY',
                'wireless_mouse',
                'wireless_net',
                'wireless_connection',
                'wireless_gamepad',
                'RECOM',
                'buka_support',
                'accessoires_kit',
                'charge_waiting_time',
                'talk_time_battery',
                'web_camera',
                'Weight',
                'A_N_Q',
                'audiotime_battery',
                'playvideo_time_batttery',
                'battery_life',
                'built_in_processor',
                'hdmi_input',
                'stylus_height',
                'hdmi_output',
                'toslink_optical_output',
                'GARANTY',
                'voice_control',
                'voice_accelerometer',
                'voice_dial',
                'voice_notifications',
                'GPU_NAME',
                'gsensor',
                'sensors',
                'double_optical_sensors',
                'size',
                'diapozon_chastot',
                'selfie_camera_aperture_size',
                'camera_aperture_size',
                'length',
                'cable_length',
                'essentials',
                'DOP_SERV',
                'charge_value',
                'hdd_value',
                'camera_video_recording',
                'charge_usb',
                'charge_220v',
                'lens_cover_type',
                'video_zoom',
                'camera_zoom_photo',
                'impedans',
                'interface_withpc',
                'handsfree_on',
                'usbcable_charge',
                'hdmidigital_cableconnection',
                'memorycard_type',
                'hdmi_amount',
                'thunderbolt_amount',
                'usb3_amount',
                'amount_inbox',
                'speakers_amount',
                'BLOG_COMMENTS_CNT',
                'microphone_amount',
                'PROC_CORE_AMOUNT',
                'LAPTOP_COMUNICATION',
                'EQUIPMENT',
                'display_contrast',
                'LAPTOP_CONFIGURATIONS',
                'LAPTOP_CASE',
                'material_type',
                'dielekrik_material',
                'case_material',
                'provodnik_material',
                'material_loop',
                'power_vt',
                'charge_adapter_power',
                'MULTIMEDIA',
                'camera_lens',
                'GPU_MEMORY_VALUE',
                'SSD_VALUE',
                'RAM_VALUE',
                'OS',
                'ACESS_STR',
                'PAYMENT_DETAIL_CART',
                'SUREFACE',
                'support_devices',
                'navigation_type',
                'wifi_support',
                'monitors_support',
                'interface_dvivga',
                'internet_connection',
                'led_display_type',
                'display_cover_techs',
                'socket_cover',
                'hdmi_port',
                'usb30typeA_port',
                'usb31_port',
                'usb_typec_port',
                'usbc_port',
                'browsing_battery_time',
                'usefull_for',
                'CML2_MANUFACTURER',
                'PROCESSOR',
                'battery_work',
                'workable_distance',
                'watch_display_size',
                'loop_size',
                'camera_video_resolution',
                'selfie_camera_videoresolution_size',
                'video_slowmo_resolution',
                'camera_resolution',
                'camera_selfie_resolution',
                'connections_lightening_usb',
                'lightning_socket',
                'charge_socket',
                'input_usbc',
                'Output_usbc',
                'interface_connector',
                'SELL_PROD',
                'double_mic',
                'sense_controlpanel',
                'seriel',
                'noise_reduction_system',
                'gsm_wifi_tech',
                'YOUTUBE',
                'camera_image_stabilization',
                'CML2_TAXES',
                'manufactur_country',
                'display_techs',
                'camera_tech_essentials',
                'selfie_camera_techtype',
                'res4k_support',
                'hdr_technology',
                'simcard',
                'battery_type',
                'wirelesmouse_type',
                'TOP_FIELD_3',
                'GPU_TYPE',
                'battery_aa_aaa',
                'cable_type',
                'SSD_TYPE',
                'data_storage_type',
                'lens_type',
                'RAM_TYPE',
                'connection_type_bluetooth_usb',
                'socket_type',
                'control_type',
                'PRODUCT_OF_THE_DAY',
                'thickness',
                'proof_level',
                'water_resistance',
                'PROC_TURBOBOOST',
                'HHD',
                'video_format',
                'video_function',
                'camera_functions',
                'selfie_camera_functions',
                'wirelesscharge_support',
                'quick_charge',
                'feedback',
                'charge_case_mic',
                'CML2_ATTRIBUTES',
                'colour',
                'RAM_FREQUENCY',
                'PROC_FREQUENCY',
                'BUNDLE_BOX',
                'audiosens',
                'width',
                'CML2_BAR_CODE',
                'SCREEN_OF_LAPTOP',
                'display_brightness',
                'BS_STR',
                'SELLOUT',
            ),
            'DETAIL_META_DESCRIPTION' => '',
            'DETAIL_META_KEYWORDS' => '',
            'DETAIL_OFFERS_FIELD_CODE' => array(
                'ID',
                'CODE',
                'XML_ID',
                'NAME',
                'TAGS',
                'SORT',
                'PREVIEW_TEXT',
                'PREVIEW_PICTURE',
                'DETAIL_TEXT',
                'DETAIL_PICTURE',
                'DATE_ACTIVE_FROM',
                'ACTIVE_FROM',
                'DATE_ACTIVE_TO',
                'ACTIVE_TO',
                'SHOW_COUNTER',
                'SHOW_COUNTER_START',
                'IBLOCK_TYPE_ID',
                'IBLOCK_ID',
                'IBLOCK_CODE',
                'IBLOCK_NAME',
                'IBLOCK_EXTERNAL_ID',
                'DATE_CREATE',
                'CREATED_BY',
                'CREATED_USER_NAME',
                'TIMESTAMP_X',
                'MODIFIED_BY',
                'USER_NAME',
            ),
            'DETAIL_OFFERS_PROPERTY_CODE' => array(
                'this_prod_model',
                'watch_display_size',
                'HDD',
                'BLOG_POST_ID',
                'CML2_ARTICLE',
                'CML2_BASE_UNIT',
                'graphics_mac',
                'size_list',
                'MORE_PHOTO',
                'item_code',
                'BLOG_COMMENTS_CNT',
                'material_list',
                'NOT_EXPORT_YM',
                'OS',
                'CML2_MANUFACTURER',
                'PROC',
                'SCREEN_RES',
                'CML2_TRAITS',
                'laptop_series',
                'CML2_TAXES',
                'FILES',
                'CML2_ATTRIBUTES',
                'COLOR_REF',
                'ciferblat',
                'BUNDLE_BOX',
                'CML2_BAR_CODE',
            ),
            'DETAIL_PRODUCT_INFO_BLOCK_ORDER' => '',
            'DETAIL_PRODUCT_PAY_BLOCK_ORDER' => '',
            'DETAIL_PROPERTY_CODE' => array(
                'model',
                'CML2_ARTICLE',
                'TOP_FIELD_2',
                'SCREEN_SiZE',
                'SCREEN_RESOLUTION',
                'SCREEN_TYPE',
                'display_density_ppi',
                'DELIVERY_DETAIL_CART',
                'BLOG_POST_ID',
                'lan_socketrj45',
                'microsoft',
                'display_multitouch_option',
                'touchbar_apple',
                'automatic_on',
                'movements_accelerometer',
                'ACESS',
                'acoustic_type',
                'audio',
                'id_verification',
                'batteries_inbox',
                'BATTARY',
                'wireless_mouse',
                'wireless_net',
                'wireless_connection',
                'wireless_gamepad',
                'RECOM',
                'buka_support',
                'accessoires_kit',
                'charge_waiting_time',
                'talk_time_battery',
                'web_camera',
                'Weight',
                'A_N_Q',
                'audiotime_battery',
                'playvideo_time_batttery',
                'battery_life',
                'built_in_processor',
                'hdmi_input',
                'stylus_height',
                'hdmi_output',
                'toslink_optical_output',
                'GARANTY',
                'voice_control',
                'voice_accelerometer',
                'voice_dial',
                'voice_notifications',
                'GPU_NAME',
                'gsensor',
                'sensors',
                'double_optical_sensors',
                'size',
                'diapozon_chastot',
                'selfie_camera_aperture_size',
                'camera_aperture_size',
                'length',
                'cable_length',
                'essentials',
                'DOP_SERV',
                'charge_value',
                'hdd_value',
                'camera_video_recording',
                'charging_type',
                'charge_usb',
                'charge_220v',
                'lens_cover_type',
                'video_zoom',
                'camera_zoom_photo',
                'impedans',
                'interface_withpc',
                'handsfree_on',
                'usbcable_charge',
                'hdmidigital_cableconnection',
                'memorycard_type',
                'hdmi_amount',
                'thunderbolt_amount',
                'usb3_amount',
                'amount_inbox',
                'speakers_amount',
                'BLOG_COMMENTS_CNT',
                'microphone_amount',
                'PROC_CORE_AMOUNT',
                'LAPTOP_COMUNICATION',
                'EQUIPMENT',
                'display_contrast',
                'LAPTOP_CONFIGURATIONS',
                'LAPTOP_CASE',
                'material_type',
                'dielekrik_material',
                'case_material',
                'provodnik_material',
                'material_loop',
                'power_vt',
                'charge_adapter_power',
                'MULTIMEDIA',
                'TEXT_UNDER_PHOTO',
                'camera_lens',
                'GPU_MEMORY_VALUE',
                'SSD_VALUE',
                'RAM_VALUE',
                'OS',
                'ACESS_STR',
                'PAYMENT_DETAIL_CART',
                'SUREFACE',
                'support_devices',
                'navigation_type',
                'wifi_support',
                'monitors_support',
                'interface_dvivga',
                'internet_connection',
                'led_display_type',
                'display_cover_techs',
                'socket_cover',
                'hdmi_port',
                'usb30typeA_port',
                'usb31_port',
                'usb_typec_port',
                'usbc_port',
                'browsing_battery_time',
                'brand_rs',
                'usefull_for',
                'CML2_MANUFACTURER',
                'PROCESSOR',
                'battery_work',
                'workable_distance',
                'watch_display_size',
                'loop_size',
                'camera_video_resolution',
                'selfie_camera_videoresolution_size',
                'video_slowmo_resolution',
                'camera_resolution',
                'camera_selfie_resolution',
                'connections_lightening_usb',
                'lightning_socket',
                'charge_socket',
                'input_usbc',
                'Output_usbc',
                'interface_connector',
                'SELL_PROD',
                'double_mic',
                'sense_controlpanel',
                'seriel',
                'noise_reduction_system',
                'gsm_wifi_tech',
                'YOUTUBE',
                'camera_image_stabilization',
                'CML2_TAXES',
                'manufactur_country',
                'display_techs',
                'camera_tech_essentials',
                'selfie_camera_techtype',
                'res4k_support',
                'hdr_technology',
                'simcard',
                'battery_type',
                'wirelesmouse_type',
                'TOP_FIELD_3',
                'GPU_TYPE',
                'battery_aa_aaa',
                'cable_type',
                'SSD_TYPE',
                'data_storage_type',
                'lens_type',
                'RAM_TYPE',
                'connection_type_bluetooth_usb',
                'socket_type',
                'control_type',
                'PRODUCT_OF_THE_DAY',
                'thickness',
                'proof_level',
                'water_resistance',
                'PROC_TURBOBOOST',
                'HHD',
                'video_format',
                'video_function',
                'camera_functions',
                'selfie_camera_functions',
                'wirelesscharge_support',
                'quick_charge',
                'feedback',
                'charge_case_mic',
                'CML2_ATTRIBUTES',
                'colour',
                'RAM_FREQUENCY',
                'PROC_FREQUENCY',
                'BUNDLE_BOX',
                'audiosens',
                'width',
                'CML2_BAR_CODE',
                'SCREEN_OF_LAPTOP',
                'display_brightness',
                'BS_STR',
                'SELLOUT',
                'comp_type_chargebattery',
                'CML2_BASE_UNIT',
                'CML2_TRAITS',
                'ONLY_CASH',
            ),
            'DETAIL_SET_CANONICAL_URL' => 'N',
            'DETAIL_SET_VIEWED_IN_COMPONENT' => 'N',
            'DETAIL_SHOW_POPULAR' => 'N',
            'DETAIL_SHOW_SLIDER' => 'N',
            'DETAIL_SHOW_VIEWED' => 'N',
            'DETAIL_STRICT_SECTION_CHECK' => 'N',
            'DETAIL_USE_COMMENTS' => 'N',
            'DETAIL_USE_VOTE_RATING' => 'N',
            'DISABLE_INIT_JS_IN_COMPONENT' => 'Y',
            'DISPLAY_BOTTOM_PAGER' => 'Y',
            'DISPLAY_TOP_PAGER' => 'N',
            'ELEMENT_SORT_FIELD' => 'sort',
            'ELEMENT_SORT_FIELD2' => 'id',
            'ELEMENT_SORT_ORDER' => 'asc',
            'ELEMENT_SORT_ORDER2' => 'desc',
            'FILE_404' => '',
            'FILTER_HIDE_ON_MOBILE' => 'N',
            'FILTER_VIEW_MODE' => '',
            'GIFTS_DETAIL_BLOCK_TITLE' => '',
            'GIFTS_DETAIL_HIDE_BLOCK_TITLE' => 'N',
            'GIFTS_DETAIL_PAGE_ELEMENT_COUNT' => 0,
            'GIFTS_DETAIL_TEXT_LABEL_GIFT' => '',
            'GIFTS_MAIN_PRODUCT_DETAIL_BLOCK_TITLE' => '',
            'GIFTS_MAIN_PRODUCT_DETAIL_HIDE_BLOCK_TITLE' => 'N',
            'GIFTS_MAIN_PRODUCT_DETAIL_PAGE_ELEMENT_COUNT' => 0,
            'GIFTS_MESS_BTN_BUY' => '',
            'GIFTS_SECTION_LIST_BLOCK_TITLE' => '',
            'GIFTS_SECTION_LIST_HIDE_BLOCK_TITLE' => 'N',
            'GIFTS_SECTION_LIST_PAGE_ELEMENT_COUNT' => 0,
            'GIFTS_SECTION_LIST_TEXT_LABEL_GIFT' => '',
            'GIFTS_SHOW_DISCOUNT_PERCENT' => 'N',
            'GIFTS_SHOW_IMAGE' => 'N',
            'GIFTS_SHOW_NAME' => 'N',
            'GIFTS_SHOW_OLD_PRICE' => 'N',
            'HIDE_NOT_AVAILABLE' => 'Y',
            'HIDE_NOT_AVAILABLE_OFFERS' => 'Y',
            'IBLOCK_ID' => 6,
            'IBLOCK_TYPE' => 'catalog',
            'INCLUDE_SUBSECTIONS' => 'Y',
            'INSTANT_RELOAD' => 'N',
            'LABEL_PROP' => array(),
            'LAZY_LOAD' => 'N',
            'LINE_ELEMENT_COUNT' => 0,
            'LINK_ELEMENTS_URL' => '',
            'LINK_IBLOCK_ID' => '',
            'LINK_IBLOCK_TYPE' => '',
            'LINK_PROPERTY_SID' => '',
            'LIST_BROWSER_TITLE' => '',
            'LIST_ENLARGE_PRODUCT' => '',
            'LIST_META_DESCRIPTION' => '',
            'LIST_META_KEYWORDS' => '',
            'LIST_OFFERS_FIELD_CODE' => array(
                'ID',
                'CODE',
                'XML_ID',
                'NAME',
                'TAGS',
                'SORT',
                'PREVIEW_TEXT',
                'PREVIEW_PICTURE',
                'DETAIL_TEXT',
                'DETAIL_PICTURE',
            ),
            'LIST_OFFERS_LIMIT' => '0',
            'LIST_OFFERS_PROPERTY_CODE' => array(
                'this_prod_model',
                'watch_display_size',
                'HDD',
                'BLOG_POST_ID',
                'CML2_ARTICLE',
                'CML2_BASE_UNIT',
                'size_list',
                'MORE_PHOTO',
                'item_code',
                'BLOG_COMMENTS_CNT',
                'material_list',
                'NOT_EXPORT_YM',
                'OS',
                'CML2_MANUFACTURER',
                'PROC',
                'SCREEN_RES',
                'CML2_TRAITS',
                'laptop_series',
                'CML2_TAXES',
                'FILES',
                'CML2_ATTRIBUTES',
                'COLOR_REF',
                'ciferblat',
                'BUNDLE_BOX',
                'CML2_BAR_CODE',
                'ipad_model',
                'case_size_filter',
            ),
            'LIST_PRODUCT_BLOCKS_ORDER' => '',
            'LIST_PRODUCT_ROW_VARIANTS' => '',
            'LIST_PROPERTY_CODE' => array(
                'model',
                'CML2_ARTICLE',
                'TOP_FIELD_2',
                'SCREEN_SiZE',
                'SCREEN_RESOLUTION',
                'SCREEN_TYPE',
                'display_density_ppi',
                'DELIVERY_DETAIL_CART',
                'BLOG_POST_ID',
                'lan_socketrj45',
                'microsoft',
                'display_multitouch_option',
                'touchbar_apple',
                'automatic_on',
                'movements_accelerometer',
                'ACESS',
                'acoustic_type',
                'audio',
                'id_verification',
                'batteries_inbox',
                'BATTARY',
                'wireless_mouse',
                'wireless_net',
                'wireless_connection',
                'wireless_gamepad',
                'RECOM',
                'buka_support',
                'accessoires_kit',
                'charge_waiting_time',
                'talk_time_battery',
                'web_camera',
                'Weight',
                'A_N_Q',
                'audiotime_battery',
                'playvideo_time_batttery',
                'battery_life',
                'built_in_processor',
                'hdmi_input',
                'stylus_height',
                'hdmi_output',
                'toslink_optical_output',
                'GARANTY',
                'voice_control',
                'voice_accelerometer',
                'voice_dial',
                'voice_notifications',
                'GPU_NAME',
                'gsensor',
                'sensors',
                'double_optical_sensors',
                'size',
                'diapozon_chastot',
                'selfie_camera_aperture_size',
                'camera_aperture_size',
                'length',
                'cable_length',
                'essentials',
                'DOP_SERV',
                'charge_value',
                'hdd_value',
                'camera_video_recording',
                'charging_type',
                'charge_usb',
                'charge_220v',
                'lens_cover_type',
                'video_zoom',
                'camera_zoom_photo',
                'impedans',
                'interface_withpc',
                'handsfree_on',
                'usbcable_charge',
                'hdmidigital_cableconnection',
                'memorycard_type',
                'hdmi_amount',
                'thunderbolt_amount',
                'usb3_amount',
                'amount_inbox',
                'speakers_amount',
                'BLOG_COMMENTS_CNT',
                'microphone_amount',
                'PROC_CORE_AMOUNT',
                'LAPTOP_COMUNICATION',
                'EQUIPMENT',
                'display_contrast',
                'LAPTOP_CONFIGURATIONS',
                'LAPTOP_CASE',
                'material_type',
                'dielekrik_material',
                'case_material',
                'provodnik_material',
                'material_loop',
                'power_vt',
                'charge_adapter_power',
                'MULTIMEDIA',
                'TEXT_UNDER_PHOTO',
                'camera_lens',
                'GPU_MEMORY_VALUE',
                'SSD_VALUE',
                'RAM_VALUE',
                'OS',
                'ACESS_STR',
                'PAYMENT_DETAIL_CART',
                'SUREFACE',
                'support_devices',
                'navigation_type',
                'wifi_support',
                'monitors_support',
                'interface_dvivga',
                'internet_connection',
                'led_display_type',
                'display_cover_techs',
                'socket_cover',
                'hdmi_port',
                'usb30typeA_port',
                'usb31_port',
                'usb_typec_port',
                'usbc_port',
                'browsing_battery_time',
                'brand_rs',
                'usefull_for',
                'CML2_MANUFACTURER',
                'PROCESSOR',
                'battery_work',
                'workable_distance',
                'watch_display_size',
                'loop_size',
                'camera_video_resolution',
                'selfie_camera_videoresolution_size',
                'video_slowmo_resolution',
                'camera_resolution',
                'camera_selfie_resolution',
                'connections_lightening_usb',
                'lightning_socket',
                'charge_socket',
                'input_usbc',
                'Output_usbc',
                'interface_connector',
                'SELL_PROD',
                'double_mic',
                'sense_controlpanel',
                'seriel',
                'noise_reduction_system',
                'gsm_wifi_tech',
                'YOUTUBE',
                'camera_image_stabilization',
                'CML2_TAXES',
                'manufactur_country',
                'display_techs',
                'camera_tech_essentials',
                'selfie_camera_techtype',
                'res4k_support',
                'hdr_technology',
                'simcard',
                'battery_type',
                'wirelesmouse_type',
                'TOP_FIELD_3',
                'GPU_TYPE',
                'battery_aa_aaa',
                'cable_type',
                'SSD_TYPE',
                'data_storage_type',
                'lens_type',
                'RAM_TYPE',
                'connection_type_bluetooth_usb',
                'socket_type',
                'control_type',
                'PRODUCT_OF_THE_DAY',
                'thickness',
                'proof_level',
                'water_resistance',
                'PROC_TURBOBOOST',
                'HHD',
                'video_format',
                'video_function',
                'camera_functions',
                'selfie_camera_functions',
                'wirelesscharge_support',
                'quick_charge',
                'feedback',
                'charge_case_mic',
                'CML2_ATTRIBUTES',
                'colour',
                'RAM_FREQUENCY',
                'PROC_FREQUENCY',
                'BUNDLE_BOX',
                'audiosens',
                'width',
                'CML2_BAR_CODE',
                'SCREEN_OF_LAPTOP',
                'display_brightness',
                'BS_STR',
                'SELLOUT',
                'comp_type_chargebattery',
                'CML2_BASE_UNIT',
                'CML2_TRAITS',
            ),
            'LIST_PROPERTY_CODE_MOBILE' => array(
                'model',
                'CML2_ARTICLE',
                'TOP_FIELD_2',
                'SCREEN_SiZE',
                'SCREEN_RESOLUTION',
                'SCREEN_TYPE',
                'display_density_ppi',
                'DELIVERY_DETAIL_CART',
                'BLOG_POST_ID',
                'lan_socketrj45',
                'microsoft',
                'display_multitouch_option',
                'touchbar_apple',
                'automatic_on',
                'movements_accelerometer',
                'ACESS',
                'acoustic_type',
                'audio',
                'id_verification',
                'batteries_inbox',
                'BATTARY',
                'wireless_mouse',
                'wireless_net',
                'wireless_connection',
                'wireless_gamepad',
                'RECOM',
                'buka_support',
                'accessoires_kit',
                'charge_waiting_time',
                'talk_time_battery',
                'web_camera',
                'Weight',
                'A_N_Q',
                'audiotime_battery',
                'playvideo_time_batttery',
                'battery_life',
                'built_in_processor',
                'hdmi_input',
                'stylus_height',
                'hdmi_output',
                'toslink_optical_output',
                'GARANTY',
                'voice_control',
                'voice_accelerometer',
                'voice_dial',
                'voice_notifications',
                'GPU_NAME',
                'gsensor',
                'sensors',
                'double_optical_sensors',
                'size',
                'diapozon_chastot',
                'selfie_camera_aperture_size',
                'camera_aperture_size',
                'length',
                'cable_length',
                'essentials',
                'DOP_SERV',
                'charge_value',
                'hdd_value',
                'camera_video_recording',
                'charging_type',
                'charge_usb',
                'charge_220v',
                'lens_cover_type',
                'video_zoom',
                'camera_zoom_photo',
                'impedans',
                'interface_withpc',
                'handsfree_on',
                'usbcable_charge',
                'hdmidigital_cableconnection',
                'memorycard_type',
                'hdmi_amount',
                'thunderbolt_amount',
                'usb3_amount',
                'amount_inbox',
                'speakers_amount',
                'BLOG_COMMENTS_CNT',
                'microphone_amount',
                'PROC_CORE_AMOUNT',
                'LAPTOP_COMUNICATION',
                'EQUIPMENT',
                'display_contrast',
                'LAPTOP_CONFIGURATIONS',
                'LAPTOP_CASE',
                'material_type',
                'dielekrik_material',
                'case_material',
                'provodnik_material',
                'material_loop',
                'power_vt',
                'charge_adapter_power',
                'MULTIMEDIA',
                'TEXT_UNDER_PHOTO',
                'camera_lens',
                'GPU_MEMORY_VALUE',
                'SSD_VALUE',
                'RAM_VALUE',
                'OS',
                'ACESS_STR',
                'PAYMENT_DETAIL_CART',
                'SUREFACE',
                'support_devices',
                'navigation_type',
                'wifi_support',
                'monitors_support',
                'interface_dvivga',
                'internet_connection',
                'led_display_type',
                'display_cover_techs',
                'socket_cover',
                'hdmi_port',
                'usb30typeA_port',
                'usb31_port',
                'usb_typec_port',
                'usbc_port',
                'browsing_battery_time',
                'brand_rs',
                'usefull_for',
                'CML2_MANUFACTURER',
                'PROCESSOR',
                'battery_work',
                'workable_distance',
                'watch_display_size',
                'loop_size',
                'camera_video_resolution',
                'selfie_camera_videoresolution_size',
                'video_slowmo_resolution',
                'camera_resolution',
                'camera_selfie_resolution',
                'connections_lightening_usb',
                'lightning_socket',
                'charge_socket',
                'input_usbc',
                'Output_usbc',
                'interface_connector',
                'SELL_PROD',
                'double_mic',
                'sense_controlpanel',
                'seriel',
                'noise_reduction_system',
                'gsm_wifi_tech',
                'YOUTUBE',
                'camera_image_stabilization',
                'CML2_TAXES',
                'manufactur_country',
                'display_techs',
                'camera_tech_essentials',
                'selfie_camera_techtype',
                'res4k_support',
                'hdr_technology',
                'simcard',
                'battery_type',
                'wirelesmouse_type',
                'TOP_FIELD_3',
                'GPU_TYPE',
                'battery_aa_aaa',
                'cable_type',
                'SSD_TYPE',
                'data_storage_type',
                'lens_type',
                'RAM_TYPE',
                'connection_type_bluetooth_usb',
                'socket_type',
                'control_type',
                'PRODUCT_OF_THE_DAY',
                'thickness',
                'proof_level',
                'water_resistance',
                'PROC_TURBOBOOST',
                'HHD',
                'video_format',
                'video_function',
                'camera_functions',
                'selfie_camera_functions',
                'wirelesscharge_support',
                'quick_charge',
                'feedback',
                'charge_case_mic',
                'CML2_ATTRIBUTES',
                'colour',
                'RAM_FREQUENCY',
                'PROC_FREQUENCY',
                'BUNDLE_BOX',
                'audiosens',
                'width',
                'CML2_BAR_CODE',
                'SCREEN_OF_LAPTOP',
                'display_brightness',
                'BS_STR',
                'SELLOUT',
                'comp_type_chargebattery',
                'CML2_BASE_UNIT',
                'CML2_TRAITS',
            ),
            'LIST_SHOW_SLIDER' => 'N',
            'LIST_SLIDER_INTERVAL' => 0,
            'LIST_SLIDER_PROGRESS' => 'N',
            'LOAD_ON_SCROLL' => 'N',
            'MESSAGE_404' => '',
            'MESS_BTN_ADD_TO_BASKET' => '',
            'MESS_BTN_BUY' => '',
            'MESS_BTN_COMPARE' => '',
            'MESS_BTN_DETAIL' => '',
            'MESS_BTN_SUBSCRIBE' => '',
            'MESS_COMMENTS_TAB' => '',
            'MESS_DESCRIPTION_TAB' => '',
            'MESS_NOT_AVAILABLE' => '',
            'MESS_PRICE_RANGES_TITLE' => '',
            'MESS_PROPERTIES_TAB' => '',
            'OFFERS_CART_PROPERTIES' => array(
                'this_prod_model',
                'watch_display_size',
                'HDD',
                'BLOG_POST_ID',
                'SALES_ITEM',
                'CML2_ARTICLE',
                'CML2_BASE_UNIT',
                'size_list',
                'item_code',
                'BLOG_COMMENTS_CNT',
                'material_list',
                'NOT_EXPORT_YM',
                'NEW_ITEM',
                'OS',
                'CML2_MANUFACTURER',
                'PROC',
                'SCREEN_RES',
                'CML2_TRAITS',
                'laptop_series',
                'CML2_TAXES',
                'PRODUCT_DAY',
                'CML2_ATTRIBUTES',
                'COLOR_REF',
                'ciferblat',
                'BUNDLE_BOX',
                'CML2_BAR_CODE',
            ),
            'OFFERS_SORT_FIELD' => 'sort',
            'OFFERS_SORT_FIELD2' => 'id',
            'OFFERS_SORT_ORDER' => 'asc',
            'OFFERS_SORT_ORDER2' => 'desc',
            'OFFER_ADD_PICT_PROP' => '',
            'OFFER_TREE_PROPS' => array(
                'watch_display_size',
                'HDD',
                'COLOR_REF',
                'PROC',
                'ciferblat',
                'graphics_mac',
            ),
            'PAGER_BASE_LINK_ENABLE' => 'Y',
            'PAGER_DESC_NUMBERING' => 'N',
            'PAGER_DESC_NUMBERING_CACHE_TIME' => 36000,
            'PAGER_SHOW_ALL' => 'N',
            'PAGER_SHOW_ALWAYS' => 'N',
            'PAGER_TEMPLATE' => 'catalog_section',
            'PAGER_TITLE' => 'Товары',
            'PAGER_PARAMS_NAME' => 'arrPager',
            'PAGE_ELEMENT_COUNT' => 15,
            'PARTIAL_PRODUCT_PROPERTIES' => 'N',
            'PRICE_CODE' => array('Розничная'),
            'PRICE_VAT_INCLUDE' => 'Y',
            'PRICE_VAT_SHOW_VALUE' => 'N',
            'PRODUCT_DISPLAY_MODE' => 'N',
            'PRODUCT_ID_VARIABLE' => '',
            'PRODUCT_PROPERTIES' => array(
                'NEW_PRODUCT',
                'STOCK_PRODUCT',
                'ACESS',
                'RECOM',
                'A_N_Q',
                'DOP_SERV',
                'ACESS_STR',
                'brand_rs',
                'CML2_MANUFACTURER',
                'watch_display_size',
                'loop_size',
                'SELL_PROD',
                'YOUTUBE',
                'camera_image_stabilization',
                'CML2_TAXES',
                'PRODUCT_OF_THE_DAY',
                'CML2_ATTRIBUTES',
                'SELLOUT',
            ),
            'PRODUCT_PROPS_VARIABLE' => '',
            'PRODUCT_QUANTITY_VARIABLE' => '',
            'PRODUCT_SUBSCRIPTION' => 'N',
            'SEARCH_CHECK_DATES' => 'N',
            'SEARCH_NO_WORD_LOGIC' => 'N',
            'SEARCH_PAGE_RESULT_COUNT' => '',
            'SEARCH_RESTART' => 'N',
            'SEARCH_USE_LANGUAGE_GUESS' => 'N',
            'SECTIONS_SHOW_PARENT_NAME' => 'N',
            'SECTIONS_VIEW_MODE' => '',
            'SECTION_ADD_TO_BASKET_ACTION' => '',
            'SECTION_BACKGROUND_IMAGE' => '',
            'SECTION_COUNT_ELEMENTS' => 'N',
            'SECTION_ID_VARIABLE' => '',
            'SECTION_TOP_DEPTH' => 1,
            'SEF_FOLDER' => '/catalog2/',
            'SEF_MODE' => 'Y',
            'SEF_URL_TEMPLATES' => Array(
                'compare' => '',
                'element' => '#SECTION_CODE_PATH#/#ELEMENT_CODE#/',
                'section' => '#SECTION_CODE#/',
                'sections' => '',
                'smart_filter' => '#SECTION_CODE#/filter/#SMART_FILTER_PATH#/apply/',
            ),
            'SET_LAST_MODIFIED' => 'N',
            'SET_STATUS_404' => 'Y',
            'SET_TITLE' => 'Y',
            'SHOW_404' => 'Y',
            'SHOW_DEACTIVATED' => 'N',
            'SHOW_DISCOUNT_PERCENT' => 'N',
            'SHOW_MAX_QUANTITY' => 'N',
            'SHOW_OLD_PRICE' => 'N',
            'SHOW_PRICE_COUNT' => 1,
            'SHOW_TOP_ELEMENTS' => 'N',
            'SIDEBAR_DETAIL_SHOW' => 'N',
            'SIDEBAR_PATH' => '',
            'SIDEBAR_SECTION_SHOW' => 'N',
            'TEMPLATE_THEME' => '',
            'TOP_ADD_TO_BASKET_ACTION' => '',
            'TOP_ELEMENT_COUNT' => 0,
            'TOP_ELEMENT_SORT_FIELD' => 'sort',
            'TOP_ELEMENT_SORT_FIELD2' => 'id',
            'TOP_ELEMENT_SORT_ORDER' => 'asc',
            'TOP_ELEMENT_SORT_ORDER2' => 'desc',
            'TOP_ENLARGE_PRODUCT' => '',
            'TOP_LINE_ELEMENT_COUNT' => 0,
            'TOP_OFFERS_FIELD_CODE' => array(),
            'TOP_OFFERS_LIMIT' => 0,
            'TOP_OFFERS_PROPERTY_CODE' => array(),
            'TOP_PRODUCT_BLOCKS_ORDER' => '',
            'TOP_PRODUCT_ROW_VARIANTS' => '',
            'TOP_PROPERTY_CODE' => array(),
            'TOP_PROPERTY_CODE_MOBILE' => array(),
            'TOP_SHOW_SLIDER' => 'N',
            'TOP_SLIDER_INTERVAL' => 0,
            'TOP_SLIDER_PROGRESS' => 'N',
            'TOP_VIEW_MODE' => '',
            'USER_CONSENT' => 'N',
            'USER_CONSENT_ID' => 0,
            'USER_CONSENT_IS_CHECKED' => 'N',
            'USER_CONSENT_IS_LOADED' => 'N',
            'USE_BIG_DATA' => 'N',
            'USE_COMMON_SETTINGS_BASKET_POPUP' => 'N',
            'USE_COMPARE' => 'N',
            'USE_ELEMENT_COUNTER' => 'N',
            'USE_ENHANCED_ECOMMERCE' => 'N',
            'USE_FILTER' => 'Y',
            'USE_GIFTS_DETAIL' => 'N',
            'USE_GIFTS_MAIN_PR_SECTION_LIST' => 'N',
            'USE_GIFTS_SECTION' => 'N',
            'USE_MAIN_ELEMENT_SECTION' => 'N',
            'USE_PRICE_COUNT' => 'N',
            'USE_PRODUCT_QUANTITY' => 'N',
            'USE_REVIEW' => 'N',
            'USE_SALE_BESTSELLERS' => 'N',
            'USE_STORE' => 'N',
            'DISCOUNTED_SECTION_ID' => 186,
            'FILTER_NAME' => 'catalogFilter',
            'FILTER_FIELD_CODE' => array(
                'ID',
                'CODE',
                'XML_ID',
                'NAME',
                'TAGS',
                'SORT',
                'PREVIEW_TEXT',
                'PREVIEW_PICTURE',
                'DETAIL_TEXT',
                'DETAIL_PICTURE',
                'DATE_ACTIVE_FROM',
                'ACTIVE_FROM',
                'DATE_ACTIVE_TO',
                'ACTIVE_TO',
                'SHOW_COUNTER',
                'SHOW_COUNTER_START',
                'IBLOCK_TYPE_ID',
                'IBLOCK_ID',
                'IBLOCK_CODE',
                'IBLOCK_NAME',
                'IBLOCK_EXTERNAL_ID',
                'DATE_CREATE',
                'CREATED_BY',
                'CREATED_USER_NAME',
                'TIMESTAMP_X',
                'MODIFIED_BY',
                'USER_NAME',
            ),
            'FILTER_PROPERTY_CODE' => array(
                'model',
                'CML2_ARTICLE',
                'TOP_FIELD_2',
                'SCREEN_SiZE',
                'SCREEN_RESOLUTION',
                'SCREEN_TYPE',
                'display_density_ppi',
                'DELIVERY_DETAIL_CART',
                'BLOG_POST_ID',
                'lan_socketrj45',
                'microsoft',
                'display_multitouch_option',
                'touchbar_apple',
                'automatic_on',
                'movements_accelerometer',
                'ACESS',
                'acoustic_type',
                'audio',
                'id_verification',
                'batteries_inbox',
                'BATTARY',
                'wireless_mouse',
                'wireless_net',
                'wireless_connection',
                'wireless_gamepad',
                'RECOM',
                'buka_support',
                'accessoires_kit',
                'charge_waiting_time',
                'talk_time_battery',
                'web_camera',
                'Weight',
                'A_N_Q',
                'audiotime_battery',
                'playvideo_time_batttery',
                'battery_life',
                'built_in_processor',
                'hdmi_input',
                'stylus_height',
                'hdmi_output',
                'toslink_optical_output',
                'GARANTY',
                'voice_control',
                'voice_accelerometer',
                'voice_dial',
                'voice_notifications',
                'GPU_NAME',
                'gsensor',
                'sensors',
                'double_optical_sensors',
                'size',
                'diapozon_chastot',
                'selfie_camera_aperture_size',
                'camera_aperture_size',
                'length',
                'cable_length',
                'essentials',
                'DOP_SERV',
                'charge_value',
                'hdd_value',
                'camera_video_recording',
                'charging_type',
                'charge_usb',
                'charge_220v',
                'lens_cover_type',
                'video_zoom',
                'camera_zoom_photo',
                'impedans',
                'interface_withpc',
                'handsfree_on',
                'usbcable_charge',
                'hdmidigital_cableconnection',
                'memorycard_type',
                'hdmi_amount',
                'thunderbolt_amount',
                'usb3_amount',
                'amount_inbox',
                'speakers_amount',
                'BLOG_COMMENTS_CNT',
                'microphone_amount',
                'PROC_CORE_AMOUNT',
                'LAPTOP_COMUNICATION',
                'EQUIPMENT',
                'display_contrast',
                'LAPTOP_CONFIGURATIONS',
                'LAPTOP_CASE',
                'material_type',
                'dielekrik_material',
                'case_material',
                'provodnik_material',
                'material_loop',
                'power_vt',
                'charge_adapter_power',
                'MULTIMEDIA',
                'TEXT_UNDER_PHOTO',
                'camera_lens',
                'GPU_MEMORY_VALUE',
                'SSD_VALUE',
                'RAM_VALUE',
                'OS',
                'ACESS_STR',
                'PAYMENT_DETAIL_CART',
                'SUREFACE',
                'support_devices',
                'navigation_type',
                'wifi_support',
                'monitors_support',
                'interface_dvivga',
                'internet_connection',
                'led_display_type',
                'display_cover_techs',
                'socket_cover',
                'hdmi_port',
                'usb30typeA_port',
                'usb31_port',
                'usb_typec_port',
                'usbc_port',
                'browsing_battery_time',
                'brand_rs',
                'usefull_for',
                'CML2_MANUFACTURER',
                'PROCESSOR',
                'battery_work',
                'workable_distance',
                'watch_display_size',
                'loop_size',
                'camera_video_resolution',
                'selfie_camera_videoresolution_size',
                'video_slowmo_resolution',
                'camera_resolution',
                'camera_selfie_resolution',
                'connections_lightening_usb',
                'lightning_socket',
                'charge_socket',
                'input_usbc',
                'Output_usbc',
                'interface_connector',
                'SELL_PROD',
                'double_mic',
                'sense_controlpanel',
                'seriel',
                'noise_reduction_system',
                'gsm_wifi_tech',
                'YOUTUBE',
                'camera_image_stabilization',
                'CML2_TAXES',
                'manufactur_country',
                'display_techs',
                'camera_tech_essentials',
                'selfie_camera_techtype',
                'res4k_support',
                'hdr_technology',
                'simcard',
                'battery_type',
                'wirelesmouse_type',
                'TOP_FIELD_3',
                'GPU_TYPE',
                'battery_aa_aaa',
                'cable_type',
                'SSD_TYPE',
                'data_storage_type',
                'lens_type',
                'RAM_TYPE',
                'connection_type_bluetooth_usb',
                'socket_type',
                'control_type',
                'PRODUCT_OF_THE_DAY',
                'thickness',
                'proof_level',
                'water_resistance',
                'PROC_TURBOBOOST',
                'HHD',
                'video_format',
                'video_function',
                'camera_functions',
                'selfie_camera_functions',
                'wirelesscharge_support',
                'quick_charge',
                'feedback',
                'charge_case_mic',
                'CML2_ATTRIBUTES',
                'colour',
                'RAM_FREQUENCY',
                'PROC_FREQUENCY',
                'BUNDLE_BOX',
                'audiosens',
                'width',
                'CML2_BAR_CODE',
                'SCREEN_OF_LAPTOP',
                'display_brightness',
                'BS_STR',
                'SELLOUT',
                'comp_type_chargebattery',
                'CML2_BASE_UNIT',
                'CML2_TRAITS',
            ),
            'FILTER_PRICE_CODE' => array('Розничная'),
            'FILTER_OFFERS_FIELD_CODE' => array(
                'ID',
                'CODE',
                'XML_ID',
                'NAME',
                'TAGS',
                'SORT',
                'PREVIEW_TEXT',
                'PREVIEW_PICTURE',
                'DETAIL_TEXT',
                'DETAIL_PICTURE',
                'DATE_ACTIVE_FROM',
                'ACTIVE_FROM',
                'DATE_ACTIVE_TO',
                'ACTIVE_TO',
                'SHOW_COUNTER',
                'SHOW_COUNTER_START',
                'IBLOCK_TYPE_ID',
                'IBLOCK_ID',
                'IBLOCK_CODE',
                'IBLOCK_NAME',
                'IBLOCK_EXTERNAL_ID',
                'DATE_CREATE',
                'CREATED_BY',
                'CREATED_USER_NAME',
                'TIMESTAMP_X',
                'MODIFIED_BY',
                'USER_NAME',
            ),
            'FILTER_OFFERS_PROPERTY_CODE' => array(
                'watch_display_size',
                'HDD',
                'CML2_ARTICLE',
                'graphics_mac',
                'size_list',
                'NOT_EXPORT_YM',
                'OS',
                'CML2_MANUFACTURER',
                'PROC',
                'SCREEN_RES',
                'CML2_ATTRIBUTES',
                'ciferblat',
            ),
        )
    ); ?>
</div>
<?php
require $_SERVER['DOCUMENT_ROOT'].'/bitrix/footer.php';
?>