<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Статьи");
?>
<div class="content">
	<?$APPLICATION->IncludeComponent(
		"bitrix:news",
		"articles",
		array(
			"DISPLAY_DATE" => "Y",
			"DISPLAY_PICTURE" => "Y",
			"DISPLAY_PREVIEW_TEXT" => "Y",
			"SEF_MODE" => "Y",
			"AJAX_MODE" => "N",
			"IBLOCK_TYPE" => "articles",
			"IBLOCK_ID" => "5",
			"NEWS_COUNT" => "20",
			"USE_SEARCH" => "Y",
			"USE_RSS" => "Y",
			"USE_RATING" => "Y",
			"USE_CATEGORIES" => "Y",
			"USE_REVIEW" => "Y",
			"USE_FILTER" => "Y",
			"SORT_BY1" => "ACTIVE_FROM",
			"SORT_ORDER1" => "DESC",
			"SORT_BY2" => "SORT",
			"SORT_ORDER2" => "ASC",
			"CHECK_DATES" => "Y",
			"PREVIEW_TRUNCATE_LEN" => "",
			"LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
			"LIST_FIELD_CODE" => array(
				0 => "",
				1 => "",
			),
			"LIST_PROPERTY_CODE" => array(
				0 => "",
				1 => "",
			),
			"HIDE_LINK_WHEN_NO_DETAIL" => "Y",
			"DISPLAY_NAME" => "Y",
			"META_KEYWORDS" => "-",
			"META_DESCRIPTION" => "-",
			"BROWSER_TITLE" => "NAME",
			"DETAIL_SET_CANONICAL_URL" => "Y",
			"DETAIL_ACTIVE_DATE_FORMAT" => "d.m.Y",
			"DETAIL_FIELD_CODE" => array(
				0 => "",
				1 => "",
			),
			"DETAIL_PROPERTY_CODE" => array(
				0 => "",
				1 => "",
			),
			"DETAIL_DISPLAY_TOP_PAGER" => "Y",
			"DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
			"DETAIL_PAGER_TITLE" => "Страница",
			"DETAIL_PAGER_TEMPLATE" => "",
			"DETAIL_PAGER_SHOW_ALL" => "Y",
			"DETAIL_STRICT_SECTION_CHECK" => "Y",
			"SET_TITLE" => "Y",
			"ADD_SECTIONS_CHAIN" => "N",
			"ADD_ELEMENT_CHAIN" => "Y",
			"SET_LAST_MODIFIED" => "Y",
			"PAGER_BASE_LINK_ENABLE" => "Y",
			"SET_STATUS_404" => "N",
			"SHOW_404" => "N",
			"MESSAGE_404" => "",
			"PAGER_BASE_LINK" => "",
			"PAGER_PARAMS_NAME" => "arrPager",
			"INCLUDE_IBLOCK_INTO_CHAIN" => "Y",
			"USE_PERMISSIONS" => "Y",
			"GROUP_PERMISSIONS" => array(
				0 => "2",
			),
			"CACHE_TYPE" => "A",
			"CACHE_TIME" => "3600",
			"CACHE_FILTER" => "N",
			"CACHE_GROUPS" => "N",
			"DISPLAY_TOP_PAGER" => "Y",
			"DISPLAY_BOTTOM_PAGER" => "Y",
			"PAGER_TITLE" => "Новости",
			"PAGER_SHOW_ALWAYS" => "Y",
			"PAGER_TEMPLATE" => "",
			"PAGER_DESC_NUMBERING" => "N",
			"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
			"PAGER_SHOW_ALL" => "Y",
			"FILTER_NAME" => "",
			"FILTER_FIELD_CODE" => array(
				0 => "",
				1 => "",
			),
			"FILTER_PROPERTY_CODE" => array(
				0 => "",
				1 => "",
			),
			"NUM_NEWS" => "20",
			"NUM_DAYS" => "30",
			"YANDEX" => "Y",
			"MAX_VOTE" => "5",
			"VOTE_NAMES" => array(
				0 => "0",
				1 => "1",
				2 => "2",
				3 => "3",
				4 => "4",
				5 => "",
			),
			"CATEGORY_IBLOCK" => array(
			),
			"CATEGORY_CODE" => "CATEGORY",
			"CATEGORY_ITEMS_COUNT" => "5",
			"MESSAGES_PER_PAGE" => "10",
			"USE_CAPTCHA" => "Y",
			"REVIEW_AJAX_POST" => "N",
			"PATH_TO_SMILE" => "/bitrix/images/forum/smile/",
			"FORUM_ID" => "",
			"URL_TEMPLATES_READ" => "",
			"SHOW_LINK_TO_FORUM" => "Y",
			"POST_FIRST_MESSAGE" => "Y",
			"SEF_FOLDER" => "/articles/",
			"AJAX_OPTION_JUMP" => "N",
			"AJAX_OPTION_STYLE" => "Y",
			"AJAX_OPTION_HISTORY" => "N",
			"USE_SHARE" => "Y",
			"SHARE_HIDE" => "Y",
			"SHARE_TEMPLATE" => "",
			"SHARE_HANDLERS" => array(
				0 => "twitter",
				1 => "facebook",
				2 => "delicious",
				3 => "lj",
			),
			"SHARE_SHORTEN_URL_LOGIN" => "",
			"SHARE_SHORTEN_URL_KEY" => "",
			"COMPONENT_TEMPLATE" => "articles",
			"AJAX_OPTION_ADDITIONAL" => "",
			"STRICT_SECTION_CHECK" => "Y",
			"DISPLAY_AS_RATING" => "rating",
			"SEF_URL_TEMPLATES" => array(
				"news" => "",
				"section" => "",
				"detail" => "#ELEMENT_CODE#/",
				"search" => "search/",
				"rss" => "rss/",
				"rss_section" => "#SECTION_ID#/rss/",
			)
		),
		false
	);?>
</div>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>
